# tasks file for beid
- name: Check if eid packages are not installed yet
  stat:
    path: /usr/bin/eid-viewer
  register: eid_installed

- name: Install eid repo
  package:
    name: "{{ eid_url }}"
    state: installed
  when: eid_installed.stat.exists == false
  # notify:
  #   - clean up temp files

- name: Install eid packages
  package:
    name: "{{ eid_packages }}"
    state: present
  when: eid_installed.stat.exists == false
