# tasks file for beid

- name: Check if eid packages are not installed yet
  stat:
    path: /usr/bin/eid-viewer
  register: eid_installed

- name: Download eid repo
  get_url: 
    url: "{{ eid_url }}"
    dest: "{{ ansible_env.HOME }}/eid-archive_{{ eid_version }}_all.deb"
  when: eid_installed.stat.exists == false

- name: Install eid repo
  apt:
    deb: "{{ ansible_env.HOME }}/eid-archive_{{ eid_version }}_all.deb"
    state: installed
  when: eid_installed.stat.exists == false
  notify:
    - clean up temp files
    - run apt-get update

- meta: flush_handlers

- name: Install eid packages
  apt:
    name: "{{ eid_packages }}"
    state: present

  when: eid_installed.stat.exists == false
  register: eid_install
  notify:
    - clean up temp files

- name: Install Java browser plugin
  apt:
    name: "{{ eid_browser_packages }}"
    state: present
  when: eid_install | succeeded

#- name: Check if Firefox is installed
#  command: dpkg-query -W 'firefox'
#  register: eid_firefox
#
#- name: Install Firefox extension
#  apt:
#    name: "{{ eid_firefox_extension }}"
#    state: present
#  when: eid_firefox_extension and eid_firefox|failed 
